In [1]:
import pickle

# Путь к файлу
file_path = '/media/matykina_ov/FastSSD/nuscenes_radar_temporal_infos_test.pkl'

# Открытие и загрузка данных
with open(file_path, 'rb') as f:
    data_rctrans = pickle.load(f)

In [2]:
len(data_rctrans['infos'])

6008

In [16]:
import pickle

# Путь к файлу
file_path = '/home/matykina_ov/mini_nuscenes_radar_temporal_infos_train.pkl'

# Открытие и загрузка данных
with open(file_path, 'rb') as f:
    data_rctrans = pickle.load(f)

In [2]:
import pickle

# Загрузка данных из pkl
with open('/media/matykina_ov/FastSSD/mini_nuscenes_radar_temporal_infos_val.pkl', 'rb') as f:
    data_rctrans = pickle.load(f)

# Проход по всем записям и замена 'HPR1' на 'HPR3'
for info in data_rctrans['infos']:
    # Обновляем lidar_path
    if 'lidar_path' in info:
        info['lidar_path'] = info['lidar_path'].replace('../HPR3', '/home/docker_rctrans/HPR3')

    # Обновляем пути камер
    for cam in ['CAM_FRONT', 'CAM_BACK', 'CAM_FRONT_LEFT', 'CAM_BACK_LEFT', 'CAM_FRONT_RIGHT', 'CAM_BACK_RIGHT']:
        if cam in info['cams'] and 'data_path' in info['cams'][cam]:
            info['cams'][cam]['data_path'] = info['cams'][cam]['data_path'].replace('../HPR3', '/home/docker_rctrans/HPR3')

    # Обновляем пути радаров
    for radar in ['RADAR_FRONT', 'RADAR_FRONT_LEFT', 'RADAR_FRONT_RIGHT', 'RADAR_BACK_LEFT', 'RADAR_BACK_RIGHT']:
        if radar in info['radars']:
            for i in range(len(info['radars'][radar])):  # Если в `radars[radar]` список
                if 'data_path' in info['radars'][radar][i]:
                    info['radars'][radar][i]['data_path'] = info['radars'][radar][i]['data_path'].replace('../HPR3', '/home/docker_rctrans/HPR3')

# Сохранение обновленных данных обратно в pkl
with open('/media/matykina_ov/FastSSD/mini_nuscenes_radar_temporal_infos_val.pkl', 'wb') as f:
    pickle.dump(data_rctrans, f)


In [3]:
len(data_rctrans['infos'])

323

In [4]:
# Путь к файлу
file_path = '/media/matykina_ov/HPR1/nuscenes_infos_test.pkl'

# Открытие и загрузка данных
with open(file_path, 'rb') as f:
    data_bevdepth = pickle.load(f)

In [5]:
type(data_rctrans)

dict

In [4]:
type(data_bevdepth)

list

In [3]:
data_rctrans.keys()

dict_keys(['infos', 'metadata'])

In [6]:
len(data_bevdepth)

6008

In [7]:
data_bevdepth[0].keys()

dict_keys(['sample_token', 'timestamp', 'scene_token', 'cam_infos', 'lidar_infos', 'cam_sweeps', 'lidar_sweeps', 'ann_infos'])

In [8]:
data_bevdepth[0]['cam_infos']['CAM_FRONT'].keys()

dict_keys(['sample_token', 'ego_pose', 'timestamp', 'is_key_frame', 'height', 'width', 'filename', 'calibrated_sensor'])

In [9]:
data_bevdepth[0]['cam_infos']['CAM_FRONT']['calibrated_sensor']

{'token': '9cfda43383aa4f989cc07b134985425e',
 'sensor_token': '725903f5b62f56118f4094b46a4470d8',
 'translation': [1.72200568478, 0.00475453292289, 1.49491291905],
 'rotation': [0.5077241387638071,
  -0.4973392230703816,
  0.49837167536166627,
  -0.4964832014373754],
 'camera_intrinsic': [[1252.8131021185304, 0.0, 826.588114781398],
  [0.0, 1252.8131021185304, 469.9846626224581],
  [0.0, 0.0, 1.0]]}

In [4]:
len(data_rctrans['infos'])

6008

In [6]:
data_rctrans['infos'][0].keys()

dict_keys(['lidar_path', 'token', 'prev', 'next', 'sweeps', 'frame_idx', 'cams', 'radars', 'scene_token', 'lidar2ego_translation', 'lidar2ego_rotation', 'ego2global_translation', 'ego2global_rotation', 'timestamp', 'gt_boxes', 'gt_names', 'gt_velocity', 'num_lidar_pts', 'num_radar_pts', 'valid_flag', 'bboxes2d', 'bboxes3d_cams', 'labels2d', 'centers2d', 'depths', 'bboxes_ignore', 'visibilities'])

In [9]:
data_rctrans['infos'][0]['cams']['CAM_FRONT']['data_path']

'../HPR2/nuscenes/samples/CAM_FRONT/n015-2018-07-24-11-22-45+0800__CAM_FRONT__1532402927612460.jpg'

In [13]:
data_rctrans['infos'][0]['radars']['RADAR_BACK_LEFT'][0].keys()

dict_keys(['data_path', 'type', 'sample_data_token', 'sensor2ego_translation', 'sensor2ego_rotation', 'ego2global_translation', 'ego2global_rotation', 'timestamp', 'sensor2lidar_rotation', 'sensor2lidar_translation'])

In [10]:
data_rctrans['infos'][0].keys()

dict_keys(['lidar_path', 'token', 'prev', 'next', 'sweeps', 'frame_idx', 'cams', 'radars', 'scene_token', 'lidar2ego_translation', 'lidar2ego_rotation', 'ego2global_translation', 'ego2global_rotation', 'timestamp', 'gt_boxes', 'gt_names', 'gt_velocity', 'num_lidar_pts', 'num_radar_pts', 'valid_flag', 'bboxes2d', 'bboxes3d_cams', 'labels2d', 'centers2d', 'depths', 'bboxes_ignore', 'visibilities'])

In [30]:
data_rctrans['infos'][0]['lidar_path']
data_rctrans['infos'][0]['cams']['CAM_BACK']['data_path']
data_rctrans['infos'][0]['radars']['RADAR_FRONT'][0]['data_path']

'../HPR3/nuscenes/samples/RADAR_FRONT/n008-2018-08-01-16-03-27-0400__RADAR_FRONT__1533153857976557.pcd'

In [27]:
data_rctrans['infos'][0]['radars'].keys()

dict_keys(['RADAR_FRONT', 'RADAR_FRONT_LEFT', 'RADAR_FRONT_RIGHT', 'RADAR_BACK_LEFT', 'RADAR_BACK_RIGHT'])

In [3]:
data_rctrans['infos'][0]['cams']['CAM_FRONT'].keys()

dict_keys(['data_path', 'type', 'sample_data_token', 'sensor2ego_translation', 'sensor2ego_rotation', 'ego2global_translation', 'ego2global_rotation', 'timestamp', 'sensor2lidar_rotation', 'sensor2lidar_translation', 'cam_intrinsic'])

In [4]:
data_rctrans['infos'][0]['cams']['CAM_FRONT']['cam_intrinsic']

array([[1.26641720e+03, 0.00000000e+00, 8.16267020e+02],
       [0.00000000e+00, 1.26641720e+03, 4.91507066e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [8]:
data_rctrans['infos'][0]['radars']['RADAR_FRONT'][0]

{'data_path': '../HPR2/nuscenes/samples/RADAR_FRONT/n015-2018-07-24-11-22-45+0800__RADAR_FRONT__1532402927664178.pcd',
 'type': 'RADAR_FRONT',
 'sample_data_token': '37091c75b9704e0daa829ba56dfa0906',
 'sensor2ego_translation': [3.412, 0.0, 0.5],
 'sensor2ego_rotation': [0.9999984769132877, 0.0, 0.0, 0.0017453283658983088],
 'ego2global_translation': [411.25243634487725, 1180.7511754315697, 0.0],
 'ego2global_rotation': [0.5721129977125774,
  -0.0014962022442161157,
  0.011922678049447764,
  -0.8200867813684729],
 'timestamp': 1532402927664178,
 'sensor2lidar_rotation': array([[-0.00165874, -0.99998137, -0.00587372],
        [ 0.99971658, -0.00151875, -0.02375837],
        [ 0.02374901, -0.00591147,  0.99970047]]),
 'sensor2lidar_translation': array([ 0.01279837,  2.64863774, -1.27639935])}

In [5]:
print(data_rctrans['infos'][0]['cams']['CAM_FRONT']['ego2global_rotation'])
print(data_rctrans['infos'][0]['cams']['CAM_FRONT']['ego2global_translation'])

print(data_rctrans['infos'][0]['cams']['CAM_FRONT']['sensor2ego_rotation'])
print(data_rctrans['infos'][0]['cams']['CAM_FRONT']['sensor2ego_translation'])


[0.5720063498929273, -0.0021434844534272707, 0.011564094980151613, -0.8201648693182716]
[411.4199861830012, 1181.197175631848, 0.0]
[0.4998015430569128, -0.5030316162024876, 0.4997798114386805, -0.49737083824542755]
[1.70079118954, 0.0159456324149, 1.51095763913]


In [25]:
print(data_rctrans['infos'][0]['cams']['CAM_FRONT']['sensor2lidar_rotation'])

[[ 0.99989998 -0.0093135  -0.0106438 ]
 [ 0.01113724  0.05463942  0.99844404]
 [-0.00871744 -0.99846271  0.05473769]]


In [20]:
data_bevdepth[0]['cam_infos']['CAM_FRONT'].keys()

dict_keys(['sample_token', 'ego_pose', 'timestamp', 'is_key_frame', 'height', 'width', 'filename', 'calibrated_sensor'])

In [23]:
print(data_bevdepth[0]['cam_infos']['CAM_FRONT']['ego_pose']['rotation'])
print(data_bevdepth[0]['cam_infos']['CAM_FRONT']['ego_pose']['translation'])

print(data_bevdepth[0]['cam_infos']['CAM_FRONT']['calibrated_sensor']['rotation'])
print(data_bevdepth[0]['cam_infos']['CAM_FRONT']['calibrated_sensor']['translation'])

[0.012355004505000388, -0.0003074225144089657, 0.025075606972543442, -0.9996091602671698]
[2377.0895143883054, 796.5771631299015, 0.0]
[0.5077241387638071, -0.4973392230703816, 0.49837167536166627, -0.4964832014373754]
[1.72200568478, 0.00475453292289, 1.49491291905]


In [13]:
data_rctrans['infos'][0]['scene_token']

'bc6a757d637f4832be68986833ec17ac'

In [14]:
data_bevdepth[0]['scene_token']

'bc6a757d637f4832be68986833ec17ac'

In [15]:
data_rctrans['infos'][0]['cams']['CAM_FRONT']['data_path']

'../HPR1/nuscenes/samples/CAM_FRONT/n008-2018-08-01-16-03-27-0400__CAM_FRONT__1533153857912404.jpg'

In [16]:
data_bevdepth[0]['cam_infos']['CAM_FRONT']['filename']

'samples/CAM_FRONT/n008-2018-08-01-16-03-27-0400__CAM_FRONT__1533153857912404.jpg'

In [8]:
import torch

origin = torch.load('/media/matykina_ov/FastSSD/RCTrans/work_dirs/tmp/epoch_1.pth')
new = torch.load('/media/matykina_ov/FastSSD/RCTrans/work_dirs/tmp2/epoch_1.pth')

In [9]:
for key in origin['state_dict']:
    if origin['state_dict'][key].equal(new['state_dict'][key]) is False and 'ema' not in key:
        print(key)

dino_weight
pts_bbox_head.coords_d
pts_bbox_head.cls_branches.0.0.weight
pts_bbox_head.cls_branches.0.0.bias
pts_bbox_head.cls_branches.0.1.weight
pts_bbox_head.cls_branches.0.1.bias
pts_bbox_head.cls_branches.0.3.weight
pts_bbox_head.cls_branches.0.3.bias
pts_bbox_head.cls_branches.0.4.weight
pts_bbox_head.cls_branches.0.4.bias
pts_bbox_head.cls_branches.0.6.weight
pts_bbox_head.cls_branches.0.6.bias
pts_bbox_head.cls_branches.1.0.weight
pts_bbox_head.cls_branches.1.0.bias
pts_bbox_head.cls_branches.1.1.weight
pts_bbox_head.cls_branches.1.1.bias
pts_bbox_head.cls_branches.1.3.weight
pts_bbox_head.cls_branches.1.3.bias
pts_bbox_head.cls_branches.1.4.weight
pts_bbox_head.cls_branches.1.4.bias
pts_bbox_head.cls_branches.1.6.weight
pts_bbox_head.cls_branches.1.6.bias
pts_bbox_head.cls_branches.2.0.weight
pts_bbox_head.cls_branches.2.0.bias
pts_bbox_head.cls_branches.2.1.weight
pts_bbox_head.cls_branches.2.1.bias
pts_bbox_head.cls_branches.2.3.weight
pts_bbox_head.cls_branches.2.3.bias
pts

In [13]:
origin['state_dict']['pts_bbox_head.cls_branches.0.0.weight']

tensor([[ 0.1531,  0.1607, -0.1420,  ..., -0.0715, -0.2578,  0.0360],
        [ 0.0477, -0.0944, -0.0552,  ..., -0.0790, -0.0877,  0.0824],
        [ 0.0519,  0.1038,  0.0293,  ...,  0.1003,  0.1486,  0.0230],
        ...,
        [ 0.0520, -0.0794,  0.0421,  ...,  0.0332,  0.1067,  0.0844],
        [-0.1268, -0.0468, -0.0777,  ...,  0.0110,  0.1691,  0.0121],
        [ 0.0244,  0.0342,  0.1415,  ..., -0.0733, -0.0155,  0.0012]])

In [15]:
new['state_dict']['pts_bbox_head.cls_branches.0.0.weight']

tensor([[ 0.1531,  0.1607, -0.1420,  ..., -0.0715, -0.2578,  0.0360],
        [ 0.0477, -0.0944, -0.0552,  ..., -0.0790, -0.0877,  0.0824],
        [ 0.0519,  0.1038,  0.0293,  ...,  0.1003,  0.1486,  0.0230],
        ...,
        [ 0.0520, -0.0794,  0.0421,  ...,  0.0332,  0.1067,  0.0844],
        [-0.1268, -0.0468, -0.0777,  ...,  0.0110,  0.1691,  0.0121],
        [ 0.0244,  0.0342,  0.1415,  ..., -0.0733, -0.0155,  0.0012]])

In [28]:
origin['state_dict']['pts_bbox_head.cls_branches.0.0.weight'][origin['state_dict']['pts_bbox_head.cls_branches.0.0.weight'] != new['state_dict']['pts_bbox_head.cls_branches.0.0.weight']]


tensor([-0.0284, -0.0235,  0.0546,  ..., -0.1537,  0.0070,  0.0785])

In [29]:
new['state_dict']['pts_bbox_head.cls_branches.0.0.weight'][origin['state_dict']['pts_bbox_head.cls_branches.0.0.weight'] != new['state_dict']['pts_bbox_head.cls_branches.0.0.weight']]


tensor([-0.0284, -0.0235,  0.0546,  ..., -0.1537,  0.0070,  0.0785])

In [1]:
import torch

sbd = torch.load('/home/matykina_ov/Sparse-Beats-Dense/checkpoints/model.ckpt')

In [12]:
print(sbd['network'].keys())
print(len(sbd['network'].keys()))

odict_keys(['G1.encoder.conv00.conv.weight', 'G1.encoder.conv00.conv.bias', 'G1.encoder.conv00.bn.weight', 'G1.encoder.conv00.bn.bias', 'G1.encoder.conv00.bn.running_mean', 'G1.encoder.conv00.bn.running_var', 'G1.encoder.conv00.bn.num_batches_tracked', 'G1.encoder.g03_0.conv_1x1_shrink.conv.weight', 'G1.encoder.g03_0.conv_1x1_shrink.conv.bias', 'G1.encoder.g03_0.conv_1x1_shrink.bn.weight', 'G1.encoder.g03_0.conv_1x1_shrink.bn.bias', 'G1.encoder.g03_0.conv_1x1_shrink.bn.running_mean', 'G1.encoder.g03_0.conv_1x1_shrink.bn.running_var', 'G1.encoder.g03_0.conv_1x1_shrink.bn.num_batches_tracked', 'G1.encoder.g03_0.conv_3x3.conv.weight', 'G1.encoder.g03_0.conv_3x3.conv.bias', 'G1.encoder.g03_0.conv_3x3.bn.weight', 'G1.encoder.g03_0.conv_3x3.bn.bias', 'G1.encoder.g03_0.conv_3x3.bn.running_mean', 'G1.encoder.g03_0.conv_3x3.bn.running_var', 'G1.encoder.g03_0.conv_3x3.bn.num_batches_tracked', 'G1.encoder.g03_0.conv_1x1_expand.conv.weight', 'G1.encoder.g03_0.conv_1x1_expand.conv.bias', 'G1.encode

In [5]:
full = torch.load('/media/matykina_ov/FastSSD/RCTrans/work_dirs/rcdetr_sbd_matrixvt_imbev_branch_from_init_on_full/best_pts_bbox_NuScenes/NDS_epoch_23.pth')

In [11]:
count=0
for key in full['state_dict'].keys():
    if 'radar_depth_model' in key and 'ema' not in key:
        print(key)
        count+=1
print(count)

radar_depth_model.G1.encoder.conv00.conv.weight
radar_depth_model.G1.encoder.conv00.conv.bias
radar_depth_model.G1.encoder.conv00.bn.weight
radar_depth_model.G1.encoder.conv00.bn.bias
radar_depth_model.G1.encoder.conv00.bn.running_mean
radar_depth_model.G1.encoder.conv00.bn.running_var
radar_depth_model.G1.encoder.conv00.bn.num_batches_tracked
radar_depth_model.G1.encoder.g03_0.conv_1x1_shrink.conv.weight
radar_depth_model.G1.encoder.g03_0.conv_1x1_shrink.conv.bias
radar_depth_model.G1.encoder.g03_0.conv_1x1_shrink.bn.weight
radar_depth_model.G1.encoder.g03_0.conv_1x1_shrink.bn.bias
radar_depth_model.G1.encoder.g03_0.conv_1x1_shrink.bn.running_mean
radar_depth_model.G1.encoder.g03_0.conv_1x1_shrink.bn.running_var
radar_depth_model.G1.encoder.g03_0.conv_1x1_shrink.bn.num_batches_tracked
radar_depth_model.G1.encoder.g03_0.conv_3x3.conv.weight
radar_depth_model.G1.encoder.g03_0.conv_3x3.conv.bias
radar_depth_model.G1.encoder.g03_0.conv_3x3.bn.weight
radar_depth_model.G1.encoder.g03_0.conv

In [13]:
full['state_dict']['radar_depth_model.G1.encoder.conv00.conv.weight'].shape

torch.Size([16, 4, 3, 3])

In [16]:
sbd['network']['G1.encoder.conv00.conv.weight'].shape


torch.Size([16, 4, 3, 3])

In [21]:
for key in sbd['network'].keys():
    if sbd['network'][key].shape == full['state_dict']['radar_depth_model.'+key].shape:
        full['state_dict']['radar_depth_model.'+key] = sbd['network'][key]

In [19]:
sbd['network']['calibrated_params_encoder.mlp.0.fully_connected.weight'].shape

torch.Size([32, 3])

In [20]:
full['state_dict']['radar_depth_model.calibrated_params_encoder.mlp.0.fully_connected.weight'].shape

torch.Size([32, 6])

In [22]:
torch.save(full, '/media/matykina_ov/FastSSD/RCTrans/work_dirs/rcdetr_sbd_matrixvt_imbev_branch_from_init_on_full/epoch23_sbd_pretrained.pth')